// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhtEvSahK09PMVKGifcBaHS-sOvi8jhxY',
    appId: '1:1066053602262:web:eb7c2efe96b0dbabea3277',
    messagingSenderId: '1066053602262',
    projectId: 'student-task-82be2',
    authDomain: 'student-task-82be2.firebaseapp.com',
    storageBucket: 'student-task-82be2.firebasestorage.app',
    measurementId: 'G-8WJYZB5DBK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDls_ayE0al3yDr1KyaABhZCWOWzKDmQlQ',
    appId: '1:1066053602262:android:12e5d9c3ffc1fbfaea3277',
    messagingSenderId: '1066053602262',
    projectId: 'student-task-82be2',
    storageBucket: 'student-task-82be2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLDPpgE3Jwj_JZ1wfvYajqb9t9C__W_Dc',
    appId: '1:1066053602262:ios:e80a1c79753e5469ea3277',
    messagingSenderId: '1066053602262',
    projectId: 'student-task-82be2',
    storageBucket: 'student-task-82be2.firebasestorage.app',
    iosBundleId: 'com.example.studentTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLDPpgE3Jwj_JZ1wfvYajqb9t9C__W_Dc',
    appId: '1:1066053602262:ios:e80a1c79753e5469ea3277',
    messagingSenderId: '1066053602262',
    projectId: 'student-task-82be2',
    storageBucket: 'student-task-82be2.firebasestorage.app',
    iosBundleId: 'com.example.studentTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhtEvSahK09PMVKGifcBaHS-sOvi8jhxY',
    appId: '1:1066053602262:web:3e89a69fd2468f15ea3277',
    messagingSenderId: '1066053602262',
    projectId: 'student-task-82be2',
    authDomain: 'student-task-82be2.firebaseapp.com',
    storageBucket: 'student-task-82be2.firebasestorage.app',
    measurementId: 'G-HW0VX4NKZ0',
  );
}
